/* CHECK_CONSTRAINTS lists all of the CHECK constraints defined in the database, with the source of the constraint definition.
*/
CREATE VIEW CHECK_CONSTRAINTS (
CONSTRAINT_NAME,
CHECK_CLAUSE )
AS
SELECT RDB$CONSTRAINT_NAME,
RDB$TRIGGER_SOURCE
FROM RDB$CHECK_CONSTRAINTS RC,RDB$TRIGGERS RT
WHERE RT.RDB$TRIGGER_NAME =RC.RDB$TRIGGER_NAME;

/* CONSTRAINTS_COLUMN_USAGE lists columns used by PRIMARY KEY and UNIQUE
constraints and those defining FOREIGN KEY constraints. 
*/
CREATE VIEW CONSTRAINTS_COLUMN_USAGE (
TABLE_NAME,
COLUMN_NAME,
CONSTRAINT_NAME )
AS
SELECT RDB$RELATION_NAME,RDB$FIELD_NAME,RDB$CONSTRAINT_NAME
FROM RDB$RELATION_CONSTRAINTS RC,RDB$INDEX_SEGMENTS RI
WHERE RI.RDB$INDEX_NAME =RC.RDB$INDEX_NAME;

/* REFERENTIAL_CONSTRAINTS lists all the referential constraints defined in a database.
*/
CREATE VIEW REFERENTIAL_CONSTRAINTS (
CONSTRAINT_NAME,
UNIQUE_CONSTRAINT_NAME,
MATCH_OPTION,
UPDATE_RULE,
DELETE_RULE )
AS
SELECT RDB$CONSTRAINT_NAME,RDB$CONST_NAME_UQ,RDB$MATCH_OPTION,
RDB$UPDATE_RULE,RDB$DELETE_RULE
FROM RDB$REF_CONSTRAINTS;

/* TABLE_CONSTRAINTS lists the table-level constraints.
*/
CREATE VIEW TABLE_CONSTRAINTS (
CONSTRAINT_NAME,
TABLE_NAME,
CONSTRAINT_TYPE,
IS_DEFERRABLE,
INITIALLY_DEFERRED )
AS
SELECT RDB$CONSTRAINT_NAME,RDB$RELATION_NAME,
RDB$CONSTRAINT_TYPE,RDB$DEFERRABLE,RDB$INITIALLY_DEFERRED
FROM RDB$RELATION_CONSTRAINTS;

/* Carriage return! */
